SELECT 
    B.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
FROM
    REST_INFO B
INNER JOIN
( SELECT
    A.FOOD_TYPE, MAX(A.FAVORITES) AS FAVORITES
FROM
    REST_INFO A
GROUP BY
    A.FOOD_TYPE 

) C
ON B.FOOD_TYPE = C.FOOD_TYPE
    AND B.FAVORITES = C.FAVORITES
ORDER BY
    B.FOOD_TYPE DESC