SELECT 
    C.PRODUCT_ID, PRODUCT_NAME, SUM(TOTAL) AS TOTAL_SALES
FROM 
( SELECT 
    A.PRODUCT_ID, B.PRODUCT_NAME, (B.PRICE*A.AMOUNT) AS TOTAL
FROM 
    (
        SELECT * FROM FOOD_ORDER FO WHERE PRODUCE_DATE >= DATE_FORMAT('20220501', '%Y%m%d') AND PRODUCE_DATE <= DATE_FORMAT('20220531', '%Y%m%d')
    ) A
INNER JOIN
    FOOD_PRODUCT B
ON A.PRODUCT_ID = B.PRODUCT_ID
) C
GROUP BY
    C.PRODUCT_ID, C.PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC, PRODUCT_ID ASC