WITH RECURSIVE FULL_HOUR AS (
    SELECT 0 AS H
    UNION ALL
    SELECT H + 1 AS HOUR
    FROM FULL_HOUR
    WHERE H < 23
)
SELECT 
    CAST(B.H AS UNSIGNED) AS HOUR
    , COALESCE(A.COUNT,0) AS COUNT
FROM
    (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT FROM ANIMAL_OUTS GROUP BY DATE_FORMAT(DATETIME, '%H') ) A
RIGHT JOIN
    FULL_HOUR B
ON
    A.HOUR = B.H
ORDER BY 
    HOUR ASC