SELECT
    D.USER_ID, D.NICKNAME, C.PRICE AS TOTAL_SALES
FROM 
(
    SELECT
        A.WRITER_ID, SUM(PRICE) AS PRICE
    FROM
        USED_GOODS_BOARD A
    LEFT OUTER JOIN
        USED_GOODS_USER B
    ON
        A.WRITER_ID = B.USER_ID
    WHERE
        A.STATUS = 'DONE'
    GROUP BY
        A.WRITER_ID
) C
LEFT OUTER JOIN
    USED_GOODS_USER D
ON
    C.WRITER_ID = D.USER_ID
WHERE 
    PRICE >= 700000
ORDER BY
    PRICE ASC