SELECT
    DATE_FORMAT(DATETIME, '%H') + 0 AS HOUR, COUNT(*) AS COUNT
FROM
    ANIMAL_OUTS
WHERE 
    DATE_FORMAT(DATETIME, '%H') >= 9 and DATE_FORMAT(DATETIME, '%H') < 20
GROUP BY
    DATE_FORMAT(DATETIME, '%H')
ORDER BY
    HOUR ASC