SELECT
    D.MEMBER_NAME, C.REVIEW_TEXT, DATE_FORMAT(C.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM 
    REST_REVIEW C
RIGHT OUTER JOIN
(
    SELECT 
        A.MEMBER_ID, A.MEMBER_NAME, COUNT(*) AS CNT
    FROM
        MEMBER_PROFILE A
    LEFT OUTER JOIN
        REST_REVIEW B
    ON A.MEMBER_ID = B.MEMBER_ID
    GROUP BY
        A.MEMBER_ID, A.MEMBER_NAME
    ORDER BY CNT DESC
    LIMIT 1
) D
ON C.MEMBER_ID = D.MEMBER_ID 
ORDER BY
    C.REVIEW_DATE ASC, REVIEW_TEXT ASC