SELECT 
    DATE_FORMAT(START_DATE, '%m') AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE 
    CAR_ID IN (
        SELECT 
            CAR_ID
        FROM 
            CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE 
            DATE_FORMAT(START_DATE, '%Y-%m') >= '2022-08' AND DATE_FORMAT(START_DATE, '%Y-%m') <= '2022-10' 
        GROUP BY 
            CAR_ID
        HAVING
            COUNT(*) >= 5
    ) AND DATE_FORMAT(START_DATE, '%Y-%m') >= '2022-08' AND DATE_FORMAT(START_DATE, '%Y-%m') <= '2022-10' 
GROUP BY
    CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m')
ORDER BY
    MONTH ASC, CAR_ID DESC