SELECT
    D.ID, F.FISH_NAME, C.LENGTH
FROM 
( 
    SELECT
        A.FISH_TYPE, MAX(A.LENGTH) AS LENGTH
    FROM 
        FISH_INFO A
    GROUP BY
        A.FISH_TYPE
    HAVING 
        COUNT(*) > 1
) C
LEFT OUTER JOIN
    FISH_INFO D
ON
    C.FISH_TYPE = D.FISH_TYPE
    AND C.LENGTH = D.LENGTH
LEFT OUTER JOIN
    FISH_NAME_INFO F
ON
    C.FISH_TYPE = F.FISH_TYPE
ORDER BY
    D.ID ASC