
SELECT FLAVOR FROM (SELECT A.FLAVOR FROM 
      (SELECT FLAVOR, SUM(TOTAL_ORDER) ASUM
       FROM FIRST_HALF 
       GROUP BY FLAVOR) A,
      (SELECT FLAVOR , SUM(TOTAL_ORDER) BSUM
       FROM JULY
       GROUP BY FLAVOR) B
      WHERE A.FLAVOR = B.FLAVOR
      ORDER BY A.ASUM+B.BSUM DESC ) 
WHERE ROWNUM <=3