SELECT
    A.CATEGORY, B.MAX_PRICE, A.PRODUCT_NAME
FROM
    FOOD_PRODUCT A
INNER JOIN
(
    SELECT
        C.CATEGORY, MAX(C.PRICE) AS MAX_PRICE
    FROM
        FOOD_PRODUCT C
    WHERE
        CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY
        CATEGORY
) B
ON
    A.CATEGORY = B.CATEGORY
    AND A.PRICE = B.MAX_PRICE
ORDER BY
    B.MAX_PRICE DESC