SELECT
    COUNT(*) AS FISH_COUNT
    , MAX(LENGTH) AS MAX_LENGTH
    , FISH_TYPE
FROM
    FISH_INFO
GROUP BY
    FISH_TYPE
HAVING
    AVG(CASE WHEN LENGTH <= 10 THEN 10 WHEN LENGTH > 10 THEN LENGTH ELSE 0 END) >= 33
ORDER BY
    FISH_TYPE ASC